### PR TITLE
man: fix -S/--slots option description in qlist.1

### PR DESCRIPTION
**Pull request by emanuele6**
I noticed that the qlist(1) man page did not mention that -S implies -I, so I wanted to fix that.

The man page was actually supposed to mention it, but man/include/qlist.optdesc.yaml was incorrectly using the "slot" key to define --slots's long description, so the man page ended up using the short description from `q list --help` instead of the longer description that contains "This flag implies -I.".

Renaming the key in the yaml file from "slot" to "slots" fixed the problem.

This patch also regenerates the man pages, and so makes qwhich.1 mention the new -r option introduced by commit ea143f7.

Signed-off-by: Emanuele Torre <torreemanuele6@gmail.com>

### CODE REVIEW

**Comment by grobian** [comment]
Thanks for spotting this!  Can you undo the changes to all manpages but qlist's one for this commit to be a bit more clean please?

**Comment by emanuele6** [comment]
I can do that manually, but there is no way to build only one man page using the script.

**Comment by grobian** [comment]
Yeah. it's a manual thing, sorry about that.  I thought you could just undo the changes from the commit.

I wonder whether I should just remove the generated versions from the repo, as the release script re-generates all of them during release (in order to set the date right, and make sure one of them wasn't forgotten).

**Comment by emanuele6** [comment]
> Yeah. it's a manual thing, sorry about that. I thought you could just undo the changes from the commit.

@grobian I already did that

**Comment by grobian** [comment]
pushed, thanks!

**Pull request closed without merging**
