### PR TITLE
Refactor qcheck: use successive fail branches

### PR DESCRIPTION
**Pull request by sbesl**
Proposal to refactor qcheck. This unnests a lot of the if-then statements and makes if-then branches fail-only.

### CODE REVIEW

**Comment by grobian** [comment]
Could you squash all commits into a single one?  You can use git rebase -i HEAD~4 and use squash, then push it again here.  Github will show the new commit.

**Comment by sbesl** [comment]
Like so?
----Origineel Bericht----
Van : notifications@github.com
Datum : 23/12/2018 10:52
Aan : portage-utils@noreply.github.com
Cc : sambesselink@planet.nl, author@noreply.github.com
Onderwerp : [SPAM] Re: [gentoo/portage-utils] Refactor qcheck: use successive fail branches (#5)
Could you squash all commits into a single one? You can use git rebase -i HEAD~4 and use squash, then push it again here. Github will show the new commit.

**Comment by grobian** [comment]
Hmmm, yeah.  I think you want to rebase next time you pull (instead of merge)  That way you don't see the commits you pulled in as new ones here.  I'll cherry-pick your refactor commit.  Thanks!

**Comment by grobian** [comment]
pushed, thanks

**Pull request closed without merging**
